# Predicting Bank Customer Behavior Using ANN

### Importing the libraries

In [58]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Importing the dataset

In [59]:
dataset = pd.read_csv('Churn_Modelling.csv')
print(dataset)
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [60]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [61]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [63]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [65]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [67]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Initializing the ANN

In [68]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [69]:
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the second hidden layer

In [70]:
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the output layer

In [71]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [75]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [76]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.3315 - accuracy: 0.8659
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3278 - accuracy: 0.8715
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3422 - accuracy: 0.8591: 0s - loss: 0.350
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8552
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8712
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3275 - accuracy: 0.8661
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3299 - accuracy: 0.8629
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8646
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3410 - accuracy: 0.8583
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - los

### Predicting the result of a single observation

We Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance:60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary:50000


**Solution**

In [78]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [79]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8605